services:

  order-postgres:
    image: postgres:16
    container_name: order-postgres
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - order-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d orderdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  payment-postgres:
    image: postgres:16
    container_name: payment-postgres
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - payment-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d paymentdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  activemq:
    image: apache/activemq-classic:6.1.6
    container_name: order-activemq
    ports:
      - "61616:61616"
      - "8161:8161"

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "8080:8080"
    depends_on:
      order-postgres:
        condition: service_healthy
      activemq:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-postgres:5432/orderdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      SPRING_ACTIVEMQ_USER: admin
      SPRING_ACTIVEMQ_PASSWORD: admin

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    ports:
      - "8081:8080"
    depends_on:
      payment-postgres:
        condition: service_healthy
      activemq:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payment-postgres:5432/paymentdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      SPRING_ACTIVEMQ_USER: admin
      SPRING_ACTIVEMQ_PASSWORD: admin


volumes:
  order-postgres-data:
  payment-postgres-data: